### ISSUE TITLE
HttpCache ContentNode listener: configure expiration environments

### ISSUE THREAD

**Issue by dantleech** [sulu-cmf/sulu#218]
Currently the enviornments in which the cache is automatically cleared is everything which is not "dev":

https://github.com/sulu-cmf/sulu/blob/develop/src/Sulu/Component/HttpCache/EventListener/ContentNodeListener.php

We should change this to explicitly define which environments to expire the cache in, e.g.

````
cache_expire_env: [ prod,staging]
````

**Comment by dantleech** [comment]
Will be fixed in #653 - this allows you to configure the cache:

````
sulu_http_cache:
    handlers:
        public:
           enabled: %kernel.debug%
`````

For example
