### ISSUE TITLE
[SecurityBundle] CreateUserCommand: only en/de can be used for locale

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#465]
<a href="https://github.com/wachterjohannes"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/1464615?v=2" /></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluSecurityBundle/issues/66

https://github.com/sulu-cmf/SuluSecurityBundle/blob/develop/Command/CreateUserCommand.php#L56

**Comment by wachterjohannes** [comment]
it is possible to choose all languages.

we only have to check if selected locale is part of following parameter:

```yml
# SULU Core Configuration
sulu_core:
    locales: ["de","en"]
```
